apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  # makes the Service accessible from outside the cluster using a port allocated on each node
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 30000  # This should be a port between 30000-32767; you can choose any available port within this range.